# Generated by Django 3.2.7 on 2021-12-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faform', '0002_alter_faclerkinformation_dept_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='faclerkinformation',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faclerkinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
